### ISSUE TITLE
serializer field for MongoDBManyToManyField

### ISSUE THREAD

**Issue by husainp** [huandzh/django-mongom2m#1]
Hi,
I am using django-mongodb-engine and django rest framework. I am using MongoDBManyToManyField between 2 models. It is working fine if I directly insert record using:

p1 = Publication(title='The Python Journal')
a1 = Article(headline='Django lets you build Web apps easily')
a1.publications.add(p1)

But how can I write serializer for the same. In which form should I post data???

**Comment by huandzh** [comment]
hi, husainp. Sorry for the late reply. I was not active in this project for several months. 

I'm also not very familiar with django rest framework.  However, according to the document per http://www.django-rest-framework.org/api-guide/fields/#custom-fields , you can write a custom field and then use it when defining serializer.

Let me know if you need further help.

**Comment by husainp** [comment]
Hi @huandzh,
I have solved that problem. Need to typecast MongoDbMaytoMany field to Listfield. One can write serializer as below. 

Take care of below things:
1) One should override to_representation function, to avoid json error while parsing data in response.
2) Since I have typecast MongoDbMaytoMany field to Listfield, One can add validate_publications function in your serializer. So that any invalid id can got caught.
My Code:

        class ArticleSerializer(serializers.ModelSerializer):
            id = serializers.PrimaryKeyRelatedField(read_only=True)
            publications = serializers.ListField(required=False)

            class Meta:
                model = Article
                fields = ('id','headline','publications',)

            def to_representation(self, obj):
                pub_serializer = PublicationSerializer(obj.publications.all(), many=True)        
                ret_data = super(serializers.ModelSerializer,self).to_representation(obj)
                ret_data['publications'] = pub_serializer.data
                return ret_data

            def validate_publications(self, value):
                """
                Check that all ids exist under publication model.
                """
                for items in value:
                    pub_data = Publication.objects.filter(id=items)
                    if not pub_data:
                        error_msg = items + " : does not exist on model publication"
                        raise serializers.ValidationError(error_msg)
                return value

**Comment by huandzh** [comment]
Hi, @husainp Thanks for the sample code. 

As long as no update is required for `django-mongom2m`, I will close this issue.
